apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pod-requeue
  namespace: system
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: pod-requeue
  template:
    metadata:
      labels:
        app: pod-requeue
    spec:
      containers:
        - name: pod-requeue
          image: deis/pod-requeue:v8
          imagePullPolicy: Always
          env:
          - name: REQUEUE_SLEEP
            value: 60
          command:
            - "/bin/bash"
            - "/pod-requeue.sh"
            # To disable dry-run uncomment the line below
            #- "--execute"
